### ISSUE TITLE
returned value in calDepthHypo 

### ISSUE THREAD

**Issue by lilipopololo** [JiayuYANG/CVP-MVSNet#28]
Hello, in modules/calDepthHypo.py, X multiply by the reprojection of X which concat with projection of X3(if I am right, X3 is projection of X plus 1 pixel in source camera).
```
            tmp1 = torch.inverse(M1)
            tmp2 = M2.unsqueeze(2)
            ans = torch.matmul(tmp1, tmp2)
```
https://github.com/ToughStoneX/Self-Supervised-MVS/blob/1420bfb1d65e16677f5488360c387b28b57770ef/jdacs-ms/models/modules.py#L192

I can't understand why the sentence above can get the delta_d(depth plus residual error?)
Can you explain why

**Comment by lilipopololo** [comment]
I know deltad only is depth change of 1 pixel in source view,
sigma deltad[i] / numview can get mean of deltad and use it as sigmentation of (-d,d).
am I right?

**Comment by lilipopololo** [comment]
sweepDepthHypo used to generate depth volume (mindepth, maxdepth), calDepthHypo generate depth volume between two depth plane (0, 2d) (d=4 was set in code)

**Comment by JiayuYANG** [comment]
Hi @lilipopololo 

In my code [here](https://github.com/JiayuYANG/CVP-MVSNet/blob/master/CVP_MVSNet/models/modules.py#L176), I used only the first source view to calculate this delta_d. 
I was intended to do that because the closest view might provide most of the information. 
Dividing this delta_d by number of source views does not make sense. 

If you want to calculate the average delta_d for all source views, you need to calculate delta_d for each of the source views, say, delta_d[0]...delta_d[nsrc] and take the average of them.

About the sweepDepthHypo, I couldn't find such function in my code.
In my code, the [calSweepingDepthHypo](https://github.com/JiayuYANG/CVP-MVSNet/blob/102766b2689b6ca83ec198dd8d5c5e9cf75e5903/CVP_MVSNet/models/net.py#L113) calculate the initial depth hypothesis by uniformly sample in the whole depth range (mindepth, maxdepth). 
The [calDepthHypo](https://github.com/JiayuYANG/CVP-MVSNet/blob/102766b2689b6ca83ec198dd8d5c5e9cf75e5903/CVP_MVSNet/models/net.py#L157) calculate the refinement depth hypothesis in the local depth searching range (-d,d).

Cheers,
Jiayu.

**Comment by chenjianqu** [comment]
I can't understand the process of calculating depth `depth_d`, what is the corresponding formula?
```python
            #计算变换矩阵（不包含旋转），用于将点从 源像素坐标系 变换到 参考像素坐标系
            A = torch.matmul(ref_intrinsics[batch],ref_extrinsics[batch][:3,:3])
            tmp = torch.matmul(src_intrinsics[batch][0],src_extrinsics[batch][0,:3,:3])
            A = torch.matmul(A,torch.inverse(tmp)) 

            tmp1 = X1_d*torch.matmul(A,X1) #将点变换到 参考像素坐标系(带有深度)
            tmp2 = torch.matmul(A,X3) #将点变换到 参考像素坐标系(无深度)

            #what is?
            M1 = torch.cat([X.t().unsqueeze(2),tmp2.t().unsqueeze(2)],axis=2)[:,1:,:]
            M2 = tmp1.t()[:,1:]
            ans = torch.matmul(torch.inverse(M1),M2.unsqueeze(2))
            delta_d = ans[:,0,0] #计算深度差
````
